"""Generate the initial D1 migration from the SQLAlchemy model metadata.

Renders every table registered on ``core.database.Base`` to SQLite DDL
(D1 is SQLite) and writes it to ``migrations/0001_initial.sql``.

Usage:
    python scripts/generate_schema.py
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from core.d1 import DIALECT  # noqa: E402
from core.database import Base  # noqa: E402
import features.tables.audit_log.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.category.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.consent.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.event_log.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.ingredient.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.inventory_item.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.notification.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.recipe.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.recipe_ingredient.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.session_.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.shopping_list_item.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.tag.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.user.models  # noqa: F401, E402 — registers tables on Base.metadata
import features.tables.user_preference.models  # noqa: F401, E402 — registers tables on Base.metadata

def generate_ddl() -> str:
    """Render all registered tables (and their indexes) as SQLite DDL."""
    statements: list[str] = []
    for table in Base.metadata.sorted_tables:
        statements.append(str(CreateTable(table).compile(dialect=DIALECT)).strip() + ";")
        for index in table.indexes:
            statements.append(str(CreateIndex(index).compile(dialect=DIALECT)).strip() + ";")
    header = "-- Migration number: 0001\n-- Generated by scripts/generate_schema.py — do not edit by hand.\n"
    return header + "\n\n".join(statements) + "\n"


if __name__ == "__main__":
    output_path = PROJECT_ROOT / "migrations" / "0001_initial.sql"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_ddl(), encoding="utf-8")
    print(f"Wrote {output_path}")
