import { Table } from "@/types/table";

export const recipeIngredientSchema: Table = {
  name: "recipe_ingredient",
  columns: [
    {
      name: "recipe_id",
      dataType: "big int",
      isNullable: false,
      isAutoIncrement: true,
      maxLength: 0,
      numericScale: 0,
      isPrimaryKey: true,
      isForeignKey: true,
      isUnique: false,
      isIndex: true,
      subDatatype: null,
      defaultSetting: "",
      numericPrecision: 64
    },
    {
      name: "ingredient_id",
      dataType: "big int",
      isNullable: false,
      isAutoIncrement: true,
      maxLength: 0,
      numericScale: 0,
      isPrimaryKey: true,
      isForeignKey: true,
      isUnique: false,
      isIndex: true,
      subDatatype: null,
      defaultSetting: "",
      numericPrecision: 64
    },
    {
      name: "quantity",
      dataType: "numeric",
      isNullable: false,
      isAutoIncrement: false,
      maxLength: 0,
      numericScale: 2,
      isPrimaryKey: false,
      isForeignKey: false,
      isUnique: false,
      isIndex: false,
      subDatatype: null,
      defaultSetting: "",
      numericPrecision: 12
    },
    {
      name: "unit",
      dataType: "text",
      isNullable: true,
      isAutoIncrement: false,
      maxLength: 0,
      numericScale: 0,
      isPrimaryKey: false,
      isForeignKey: false,
      isUnique: false,
      isIndex: false,
      subDatatype: null,
      defaultSetting: "",
      numericPrecision: 0
    },
    {
      name: "created_at",
      dataType: "timestamp with time zone",
      isNullable: false,
      isAutoIncrement: false,
      maxLength: 0,
      numericScale: 0,
      isPrimaryKey: false,
      isForeignKey: false,
      isUnique: false,
      isIndex: true,
      subDatatype: null,
      defaultSetting: "CURRENT_TIMESTAMP",
      numericPrecision: 0
    },
    {
      name: "updated_at",
      dataType: "timestamp with time zone",
      isNullable: false,
      isAutoIncrement: false,
      maxLength: 0,
      numericScale: 0,
      isPrimaryKey: false,
      isForeignKey: false,
      isUnique: false,
      isIndex: true,
      subDatatype: null,
      defaultSetting: "CURRENT_TIMESTAMP",
      numericPrecision: 0
    },
  ],
};